[tool.black]
line-length = 80
skip-string-normalization = true
target-version = ["py37", "py38", "py39"]
exclude = '''
/(
    \.pytest_cache
    \.mypy_cache
)/
'''

[tool.check-manifest]
ignore = [".gitignore"]
