# flake8: noqa
"""Add audit

Revision ID: 7d65b56bd9aa
Revises: a257f1d0be36
Create Date: 2022-02-24 23:57:18.848607

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d65b56bd9aa'
down_revision = 'a257f1d0be36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
